# Generated by Django 5.2.6 on 2025-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="fecha_nacimiento",
            field=models.DateTimeField(null=True),
        ),
    ]
