# Generated by Django 5.2.6 on 2025-09-30 22:34

import curso.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "numero_curso",
                    models.IntegerField(
                        default=curso.models.obtener_numero_random, unique=True
                    ),
                ),
                ("fecha_creacion", models.DateField(default=django.utils.timezone.now)),
                (
                    "code",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=32, unique=True
                    ),
                ),
            ],
        ),
    ]
